spring:
  # 应用程序名字
  application:
    name: reggie_take_out
  # 数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?useSSL=false&characterEncoding=utf8
      username: root
      password: 990127
# 修改文件上传最大尺寸
  servlet:
    multipart:
      # 修改文件上传大小，默认是1MB
      max-file-size: 2MB
# mybatis配置
mybatis:
  configuration:
    # 显示SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  # 给实体类包名起别名，如果有多个包，使用逗号分隔开
  type-aliases-package: com.itheima.reggie.entity,com.itheima.reggie.dto
  # 指定映射文件所在的目录
  mapper-locations: classpath:mapper/*.xml
# 分页组件配置
pagehelper:
  # 指定使用哪种数据库
  helper-dialect: mysql
  # 合理化分页：
  # true 页码小于第1页返回第1页的数据，如果大于最后1页返回最后1页的数据
  # false 如果小于第1页或大于最后1页则不返回任何数据
  reasonable: true
# 上传图片目录
reggie:
  path: e:\img\


